[build]
builder = "nixpacks"
buildCommand = "curl -fsSL https://bun.sh/install | bash && ~/.bun/bin/bun --version && cd vlayer && ~/.bun/bin/bun install"
   
[deploy]
startCommand = "export PATH=$PATH:~/.bun/bin && cd vlayer && bun run api:testnet"
restartPolicyType = "on_failure" 